name: CI

on: [push, pull_request]

jobs:
  Run-Linters-and-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo
      - run: echo "Job triggered by '${{ github.event_name }}'"
      - run: echo "Job running on '${{ runner.os }}'"
