name: CI

on: [push, pull_request]

jobs:
  Run-Linters-and-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo
      - run: echo "Job triggered by '${{ github.event_name }}'"
      - run: echo "Job running on '${{ runner.os }}'"
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
      # - name: Run unit-tests
